# Rust formatting configuration for payoff-diagram-web
# This ensures consistent code formatting across the project
# Using stable rustfmt options only

# Use 4 spaces for indentation (Rust standard)
tab_spaces = 4
hard_tabs = false

# Maximum line width
max_width = 100

# Array and struct formatting
array_width = 60
struct_lit_width = 60

# Chain formatting  
chain_width = 60

# Other formatting options
use_small_heuristics = "Default"
edition = "2021"

# Format strings
format_code_in_doc_comments = true
normalize_doc_attributes = true

# Remove extra semicolons
remove_nested_parens = true

# Format macro definitions
format_macro_matchers = true
